use std::collections::BTreeMap;
use std::fmt::Write;
use std::path::PathBuf;
use std::{env, fs};

static CONFIGS: &[(&str, usize)] = &[
    // BEGIN AUTOGENERATED CONFIG FEATURES
    // Generated by gen_config.py. DO NOT EDIT.
    ("IFACE_COUNT", 2),
    ("IFACE_ADDR_COUNT", 4),
    ("ROUTE_COUNT", 4),
    ("MULTICAST_GROUP_COUNT", 8),
    ("SLAAC_PREFIX_COUNT", 2),
    ("SLAAC_ROUTER_COUNT", 2),
    ("NEIGHBOR_CACHE_COUNT", 8),
    ("PENDING_QUEUE_COUNT", 16),
    ("UDP_SOCKET_COUNT", 4),
    ("RAW_SOCKET_COUNT", 2),
    ("TCP_SOCKET_COUNT", 4),
    ("TCP_LISTENER_COUNT", 2),
    ("UDP_RX_QUEUE_COUNT", 4),
    ("RAW_RX_QUEUE_COUNT", 4),
    ("TCP_LISTENER_BACKLOG", 4),
    ("ASSEMBLER_MAX_SEGMENT_COUNT", 4),
    ("REASSEMBLY_BUFFER_COUNT", 1),
    ("SIXLOWPAN_ADDRESS_CONTEXT_COUNT", 4),
    ("DNS_MAX_QUERY_COUNT", 4),
    ("DNS_MAX_RESULT_COUNT", 4),
    ("DNS_MAX_SERVER_COUNT", 4),
    ("DNS_MAX_NAME_SIZE", 255),
    ("DHCP_MAX_DNS_SERVER_COUNT", 3),
    ("DHCP_OPTIONS_BUF_SIZE", 128),
    // END AUTOGENERATED CONFIG FEATURES
];

struct ConfigState {
    value: usize,
    seen_feature: bool,
    seen_env: bool,
}

fn main() {
    // only rebuild if build.rs changed. Otherwise Cargo will rebuild if any
    // other file changed.
    println!("cargo:rerun-if-changed=build.rs");

    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_ALLOC");

    // Rebuild if config envvar changed.
    for (name, _) in CONFIGS {
        println!("cargo:rerun-if-env-changed=XARXA_{name}");
    }

    let mut configs = BTreeMap::new();
    for (name, default) in CONFIGS {
        configs.insert(
            *name,
            ConfigState {
                value: *default,
                seen_env: false,
                seen_feature: false,
            },
        );
    }

    // Knobs of `xarxa-driver`, handled by its own build script. Not an error
    // to see them here, but not ours either.
    let driver_configs = ["PACKET_BUF_ALIGN"];

    for (var, value) in env::vars() {
        if let Some(name) = var.strip_prefix("XARXA_") {
            if driver_configs.contains(&name) {
                continue;
            }
            let Some(cfg) = configs.get_mut(name) else {
                panic!("Unknown env var {name}")
            };

            let Ok(value) = value.parse::<usize>() else {
                panic!("Invalid value for env var {name}: {value}")
            };

            cfg.value = value;
            cfg.seen_env = true;
        }

        if let Some(feature) = var.strip_prefix("CARGO_FEATURE_")
            && let Some(i) = feature.rfind('_')
        {
            let name = &feature[..i];
            let value = &feature[i + 1..];
            if let Some(cfg) = configs.get_mut(name) {
                let Ok(value) = value.parse::<usize>() else {
                    panic!("Invalid value for feature {name}: {value}")
                };

                // envvars take priority.
                if !cfg.seen_env {
                    if cfg.seen_feature {
                        panic!("multiple values set for feature {}: {} and {}", name, cfg.value, value);
                    }

                    cfg.value = value;
                    cfg.seen_feature = true;
                }
            }
        }
    }

    let mut data = String::new();

    for (name, cfg) in &configs {
        writeln!(&mut data, "pub const {}: usize = {};", name, cfg.value).unwrap();
    }

    // Index types for handles. Without `alloc` the slabs are bounded by the
    // `*_COUNT` knobs, so a handle only needs enough bits for that count.
    // With `alloc` the knobs are ignored and handles stay `usize`.
    let alloc = env::var_os("CARGO_FEATURE_ALLOC").is_some();
    for (module, count) in [
        ("iface_index", "IFACE_COUNT"),
        ("udp_index", "UDP_SOCKET_COUNT"),
        ("raw_index", "RAW_SOCKET_COUNT"),
        ("tcp_index", "TCP_SOCKET_COUNT"),
        ("tcp_listener_index", "TCP_LISTENER_COUNT"),
        ("dns_query_index", "DNS_MAX_QUERY_COUNT"),
    ] {
        let n = configs[count].value;
        let (ty, from, to) = match n {
            _ if alloc => ("usize", "i", "i"),
            1 => ("()", "{ core::debug_assert!(i == 0); }", "{ let () = i; 0 }"),
            2..=256 => (
                "u8",
                "{ core::debug_assert!(i <= u8::MAX as usize); i as u8 }",
                "i as usize",
            ),
            257..=65536 => (
                "u16",
                "{ core::debug_assert!(i <= u16::MAX as usize); i as u16 }",
                "i as usize",
            ),
            _ => (
                "u32",
                "{ core::debug_assert!(i <= u32::MAX as usize); i as u32 }",
                "i as usize",
            ),
        };
        writeln!(&mut data, "pub mod {module} {{").unwrap();
        writeln!(&mut data, "    pub type Index = {ty};").unwrap();
        writeln!(&mut data, "    pub const fn from_usize(i: usize) -> Index {{ {from} }}").unwrap();
        writeln!(&mut data, "    pub const fn to_usize(i: Index) -> usize {{ {to} }}").unwrap();
        writeln!(&mut data, "}}").unwrap();
    }

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let out_file = out_dir.join("config.rs").to_string_lossy().to_string();
    fs::write(out_file, data).unwrap();
}
