import os

abspath = os.path.abspath(__file__)
dname = os.path.dirname(abspath)
os.chdir(dname)

features = []


def _feature(into, name, default, min=None, max=None, pow2=None, vals=None):
    vals = set(vals or [])
    if min is not None:
        val = min
        while val <= max:
            vals.add(val)
            if pow2 == True or (isinstance(pow2, int) and val >= pow2):
                val *= 2
            else:
                val += 1
    vals.add(default)

    into.append(
        {
            "name": name,
            "default": default,
            "vals": sorted(list(vals)),
        }
    )


def feature(name, default, min=None, max=None, pow2=None, vals=None):
    _feature(features, name, default, min, max, pow2, vals)


def driver_feature(name, default, min=None, max=None, pow2=None, vals=None):
    _feature(driver_features, name, default, min, max, pow2, vals)


# Packet pool. Lives in `xarxa-driver`; `xarxa` forwards these features there.
# Buffer size: 802.15.4 frames, the IPv4 and IPv6 minimums plus an Ethernet
# header, Ethernet with and without VLAN tags, and jumbo frames.
driver_feature(
    "packet_buf_size",
    default=1514,
    vals=[128, 256, 512, 590, 1024, 1294, 1514, 1518, 1522, 1536, 2048, 4096, 8192, 9018, 9022, 9216, 16384],
)

# Interfaces and tables (only bounded without `alloc`).
feature("iface_count", default=2, min=1, max=8)
feature("iface_addr_count", default=4, min=1, max=16, pow2=8)
feature("route_count", default=4, min=0, max=64, pow2=8)
feature("multicast_group_count", default=8, min=1, max=1024, pow2=8)
feature("slaac_prefix_count", default=2, min=1, max=16, pow2=8)
feature("slaac_router_count", default=2, min=1, max=16, pow2=8)

# Always bounded.
feature("neighbor_cache_count", default=8, min=1, max=1024, pow2=8)
feature("pending_queue_count", default=2, min=1, max=256, pow2=8)
feature("tx_timestamp_queue_count", default=4, min=1, max=64, pow2=8)

# Socket slabs (only bounded without `alloc`).
feature("udp_socket_count", default=4, min=1, max=64, pow2=8)
feature("raw_socket_count", default=2, min=1, max=64, pow2=8)
feature("tcp_socket_count", default=4, min=1, max=64, pow2=8)
feature("tcp_listener_count", default=2, min=1, max=64, pow2=8)

# Per-socket queues. Always bounded.
feature("udp_rx_queue_count", default=4, min=1, max=64, pow2=8)
feature("raw_rx_queue_count", default=4, min=1, max=64, pow2=8)
feature("tcp_listener_backlog", default=4, min=1, max=64, pow2=8)
feature("assembler_max_segment_count", default=4, min=1, max=32, pow2=4)

# IPv4 and 6LoWPAN reassembly (features `ipv4-reassembly`,
# `sixlowpan-reassembly`): datagrams reassembled at once.
feature("reassembly_buffer_count", default=1, min=1, max=32, pow2=4)

# 6LoWPAN address contexts per interface (feature `medium-ieee802154`). The
# context identifier is 4 bits, so 16 is the most a packet can name.
feature("sixlowpan_address_context_count", default=4, min=1, max=16)

# DNS and DHCP.
feature("dns_max_query_count", default=4, min=1, max=32, pow2=4)
feature("dns_max_result_count", default=4, min=1, max=32, pow2=4)
feature("dns_max_server_count", default=4, min=1, max=32, pow2=4)
feature("dns_max_name_size", default=255, min=64, max=255, pow2=True)
feature("dhcp_max_dns_server_count", default=3, min=1, max=8)
feature("dhcp_options_buf_size", default=128, min=16, max=1024, pow2=True)

# DHCP server (feature `dhcpv4-server`): lease table entries per interface, and
# the longest client identifier a lease can store.
feature("dhcp_server_lease_count", default=8, min=1, max=64, pow2=8)
feature("dhcp_server_client_id_size", default=24, min=8, max=64, pow2=True)

# ========= Update Cargo.toml and build.rs of both crates


def update_cargo_toml(path, feature_lists):
    """feature_lists is a list of (features, forward_to) pairs. With forward_to
    set, each feature enables the same-named feature of that crate."""
    things = ""
    for feats, forward_to in feature_lists:
        for f in feats:
            name = f["name"].replace("_", "-")
            for val in f["vals"]:
                if forward_to:
                    things += f'{name}-{val} = ["{forward_to}/{name}-{val}"]'
                else:
                    things += f"{name}-{val} = []"
                if val == f["default"]:
                    things += " # Default"
                things += "\n"
            things += "\n"

    SEPARATOR_START = "# BEGIN AUTOGENERATED CONFIG FEATURES\n"
    SEPARATOR_END = "# END AUTOGENERATED CONFIG FEATURES\n"
    HELP = "# Generated by gen_config.py. DO NOT EDIT.\n"
    with open(path, "r") as f:
        data = f.read()
    before, data = data.split(SEPARATOR_START, maxsplit=1)
    _, after = data.split(SEPARATOR_END, maxsplit=1)
    data = before + SEPARATOR_START + HELP + things + SEPARATOR_END + after
    with open(path, "w") as f:
        f.write(data)


def update_build_rs(path, feats):
    things = ""
    for f in feats:
        name = f["name"].upper()
        things += f'    ("{name}", {f["default"]}),\n'

    SEPARATOR_START = "// BEGIN AUTOGENERATED CONFIG FEATURES\n"
    SEPARATOR_END = "// END AUTOGENERATED CONFIG FEATURES\n"
    HELP = "    // Generated by gen_config.py. DO NOT EDIT.\n"
    with open(path, "r") as f:
        data = f.read()
    before, data = data.split(SEPARATOR_START, maxsplit=1)
    _, after = data.split(SEPARATOR_END, maxsplit=1)
    data = before + SEPARATOR_START + HELP + things + "    " + SEPARATOR_END + after
    with open(path, "w") as f:
        f.write(data)


update_cargo_toml("Cargo.toml", [(features, None)])
update_build_rs("build.rs", features)
